### ISSUE TITLE
`POST http://localhost:4567/compile 500 (Internal Server Error)` when using Less

### ISSUE THREAD

**Issue by mattscilipoti** [jshawl/precess#3]
During class today, you got an error when attempting to use Less.

My server error is:

```
Errno::ECONNREFUSED - Connection refused - connect(2) for "localhost" port 3000:
```

Leading me to `app.rb:66`:

```
ls = RestClient.post('http://localhost:3000/less', {...
```

This code is changed significantly in your `origin/realign` branch.

**Comment by jshawl** [comment]
:+1: `forever` stopped running after a reboot :(. thanks for the detailed description!
